---
functional:
  - Пользователи могут создавать аккаунты и входить в систему с использованием уникальных идентификаторов.
  - Пользователи могут выбирать задачу для решения.
  - Пользователи могут участвовать в соревнованиях с другими игроками, решая одну и ту же задачу.
  - Пользователи могут видеть результаты сравнения своего кода с кодом соперника.
  - Рейтинги пользователей рассчитываются на основе их успеха в соревнованиях.
  - Пользователи могут играть с ботом, чтобы тренировать свои навыки.
  - Пользователи могут приглашать друзей для совместных соревнований.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования.
  - Сайт должен предоставлять интуитивно понятный интерфейс для пользователей всех уровней навыков программирования.
  - Сайт должен обеспечивать безопасность данных пользователей, включая аутентификацию и защиту от несанкционированного доступа.
  - Сайт должен быть оптимизирован для быстрой загрузки страниц и выполнения действий, чтобы обеспечивать плавный опыт пользователя.
  - Сайт должен быть совместим с последними версиями популярных веб-браузеров, таких как Chrome, Firefox, Safari и Edge.
  - Сайт должен быть способен обрабатывать большое количество трафика и поддерживать до 1000 одновременных пользователей без значительного снижения производительности.
implicit:
  - Сайт должен обеспечивать возможность восстановления пароля для пользователей, которые забыли свои учетные данные.
  - Сайт должен предоставлять обучение и инструкции для пользователей, чтобы помочь им понять возможности системы.
